### ISSUE TITLE
generic json

### ISSUE THREAD

**Issue by Maatary** [azhur/kafka-serde-scala#110]
Is there a way to just encode the generic circe json object and send it ? Such as we have GenericAvro Record, or Generic Json from Gson see https://github.com/fabiojose/gson-serde, or again Generic Json with Jackson JsonNode from confluent https://github.com/axbaretto/kafka/blob/master/connect/json/src/main/java/org/apache/kafka/connect/json/JsonSerializer.java

**Comment by azhur** [comment]
yes, all you need is to have Encoder[Json] impilcit in scope:
```scala
class CirceSupportPlainJsonSpec extends FreeSpec with Matchers {
  import CirceSupport._
  import Encoder.encodeJson

  "should serialize plain Json" in {
    val serializer    = implicitly[Serializer[Json]]
    val json          = Json.fromJsonObject(JsonObject.fromMap(Map("a" -> Json.fromInt(10))))
    val expectedBytes = """{"a":10}""".getBytes(UTF_8)
    val bytes         = serializer.serialize("unused_topic", json)
    bytes shouldBe expectedBytes
  }
}
```
