### ISSUE TITLE
Support for serdes in windows?

### ISSUE THREAD

**Issue by meddulla** [azhur/kafka-serde-scala#145]
I'm not sure if I'm missing something but would really appreciate some help. If I use no windows the implicits are found, for example:

```
// All good
object CustomerStream extends App with PlayJsonSupport {

  val totalPagesCounts: KTable[String, Long] = inputStream
    .filter((_ , ev) => ev.eventData.evData.pageType.isDefined && ev.eventData.custData.customerUid.isDefined)
    .groupBy((_, ev) => ev.eventData.custData.customerUid.get)
    //.windowedBy(SessionWindows.with(Duration.ofHours(3))
    .count()
  totalPagesCounts.toStream.to("total_pageviews")

}
```
but if I use windows, the produced implicits are not found (`Produced[Windowed[String], Long]`):

```
object CustomerStream extends App with PlayJsonSupport {
 // Error
  val totalPagesCounts: KTable[Windowed[String], Long] = inputStream
    .filter((_ , ev) => ev.eventData.evData.pageType.isDefined && ev.eventData.custData.customerUid.isDefined)
    .groupBy((_, ev) => ev.eventData.custData.customerUid.get)
    .windowedBy(TimeWindows.of(Duration.ofSeconds(5)))
    .count()
  totalPagesCounts.toStream.to("total_pageviews") \\ -> No implicits found for parameter produced: Produced[Windowed[String], Long]

}
```

Any idea why?

Thanks!

**Comment by azhur** [comment]
@meddulla 

the implicit won't be resolved for Windowed[T] because this library doesn't provide play json encoders/decoders for Windowed type. 

you can implement a play encoder/decoder for Windowed[T], import it before your topology is created.

this is a nice to have feature but unfortunately it's not supported yet

**Comment by meddulla** [comment]
Hi @azhur Thanks for clearing that up for me. Do you by any chance have any pointers on how to do this? Just got back to scala after some years and it seems like I'm starting all over again..
