### ISSUE TITLE
Add support for scala 2.13

### ISSUE THREAD

**Issue by monksy** [azhur/kafka-serde-scala#156]
Is it possible that we can get a compile going for a 2.13 version of this?

**Comment by azhur** [comment]
I hope I'll do that in the next few weeks. any help is appreciated here :)

**Comment by plokhotnyuk** [comment]
I've submitted a PR with all integration (except for Avro) migrated to Scala 2.13: https://github.com/azhur/kafka-serde-scala/pull/167/files

BEWARE: Play-JSON, circe, and uPickle dropped Scala 2.11 support.

**Comment by azhur** [comment]
I've released 0.5.0 which contains scala 2.13 along with other libraries bumping.
