### ISSUE TITLE
Can we get an example of a json4s Serdes?

### ISSUE THREAD

**Issue by monksy** [azhur/kafka-serde-scala#157]
The Circe example just auto imports everything and doesn't show what you would need to do in respect to other libraries.

**Comment by azhur** [comment]
@monksy sorry for so long delay in response.
to use json4s you need to follow the same pattern as with circe:
 - extend json4s Json4sSupport trait (or import Json4sSupport._)
 - have in scope implicit Serialization and Formats which will be used to serialize/deserialize your classes to/from bytes.

you can look at https://github.com/azhur/kafka-serde-scala/blob/master/kafka-serde-json4s/src/test/scala/io/github/azhur/kafkaserdejson4s/Json4sSupportSpec.scala for more details. Let me know if you have more questions.
